### ISSUE TITLE
Deprecated sam_description

### ISSUE THREAD

**Issue by aldoteran** [smarc-project/sam_common#17]
The URDF files on the sam_description package are old and seem to be wrong if compared to the real Sam. Both files have different origins placed at positions that now seem arbitrary, making it hard to add links.

**Comment by nilsbore** [comment]
As far as I recall, the origin is the same as the original mesh, and should be in the center of the joint between the body and the nose cone. It should be fairly straightforward to move though. If you do, don't forget to make the changes to these files in the sim as well: https://github.com/smarc-project/smarc_stonefish_sims/blob/noetic-devel/sam_stonefish_sim/data/sam_auv/sam_auv.xml , https://github.com/smarc-project/smarc_stonefish_sims/blob/noetic-devel/sam_stonefish_sim/data/sam_auv/sam_auv_no_payload_sensors.xml

**Comment by aldoteran** [comment]
Hola Nils!

Only the description used for the Stonefish simulator is using the origin where you mention. The files in sam_description have the origin in the (geometrical?) center of Sam's hull and the other one is (we assume) on the propeller shaft. 

We're updating the files and the meshes and will make a PR soon.
